# get mutation rate info
from stdpopsim import homo_sapiens
chrom = homo_sapiens.genome.chromosomes["chr22"]

# get working dir
import os
cwd = os.getcwd()

rule all:
    input:
        "simulated.trees",
        "sp_out/simulated_estimated_Ne.txt",
        "sp_out/simulated_Ne_est.png"

rule simulation:
    output:
        "simulated.trees"
    message:
        "doing simulation of GutenkunstThreePopOutOfAfrica model"
    shell:
        "python3 GutenkunstThreePopOutOfAfrica.py"


rule stairwayplot_analysis:
    input:
        rules.simulation.output
    output:
        "sp_out/simulated_estimated_Ne.txt",
        "sp_out/simulated_Ne_est.png"
    message:
        "running stairwayplot"
    shell:
        "python3 ../msp_to_stairwayplot.py {input} "+ cwd + "/sp_out 10 ../stairwayplot 10 123 " + str(chrom.mean_mutation_rate) + " 10 T"

rule clean:
    shell:
        "rm -rf sp_out simulated.trees"
