import pathlib
import sys

import numpy as np
import stdpopsim

import stairway
import simulations
import plots


stairwayplot_code = "stairwayplot/swarmops.jar"
genetic_map_downloaded_flag= ".genetic_map_downloaded"

seed = 12345
np.random.seed(seed)

reps = 2
seed_array = np.random.random_integers(1,2**31,reps)
chrm_list = ["chr22"]
rule all:
   input:
       expand("homo_sapiens_Gutenkunst/{seeds}.{chrms}.estimated_Ne.png",
		seeds=seed_array, chrms=chrm_list),
       "homo_sapiens_Gutenkunst/estimated_Ne.png"

rule sp_download:
    output:
        stairwayplot_code
    message:
        "downloading stairwayplot"
    shell:
        "wget http://sesame.uoregon.edu/~adkern/stdpopsim/stairwayplot.tar.gz && \
        tar zxf stairwayplot.tar.gz"


rule download_genetic_map:
    output: genetic_map_downloaded_flag
    message: "Downloading default genetic map"
    run:
        # We need to have this here to avoid several threads trying to download the 
        # the genetic map into the cache at the same time.
        genetic_map = stdpopsim.homo_sapiens.HapmapII_GRCh37()
        if not genetic_map.is_cached():
            genetic_map.download()
        with open(output[0], "w") as f:
            print("File to indicate genetic map has been downloaded", file=f)

rule homo_sapiens_Gutenkunst_simulation:
    input: genetic_map_downloaded_flag
    output:
        "homo_sapiens_Gutenkunst/{seeds}.{chrms}.trees"
    # TODO get simulation parameters from stdpopsim, so we can share them easily 
    # with anlysis code below?
    run: simulations.homo_sapiens_Gutenkunst(output[0], wildcards.seeds, wildcards.chrms)

rule homo_sapiens_Gutenkunst_stairwayplot:
    input:
        "homo_sapiens_Gutenkunst/{seeds}.{chrms}.trees",
        stairwayplot_code,
    output:
        "homo_sapiens_Gutenkunst/{seeds}.{chrms}.estimated_Ne.txt"
    threads: 8
    run: 
        runner = stairway.StairwayPlotRunner(
            workdir="homo_sapiens_Gutenkunst/stairwayplot/"+wildcards.seeds+"/",
            stairway_dir=pathlib.Path.cwd() / "stairwayplot")
        runner.ts_to_stairway(input[0], num_bootstraps=10)
        runner.run_theta_estimation(max_workers=threads, show_progress=True)
        # TODO get the rate here from stdpopsim. 
        runner.run_summary(output[0], mutation_rate=1e-8, generation_time=10)

rule homo_sapiens_Gutenkunst_stairwayplot_plot:
    input:
        "homo_sapiens_Gutenkunst/{seeds}.{chrms}.estimated_Ne.txt"
    output:
        "homo_sapiens_Gutenkunst/{seeds}.{chrms}.estimated_Ne.png"
    run: plots.plot_stairway_Ne_estimate(input[0], output[0])

def ne_files(wildcards):
    return(expand("homo_sapiens_Gutenkunst/{seeds}.{chrms}.estimated_Ne.txt",
            seeds=seed_array, chrms=chrm_list))

rule homo_sapiens_compound_stairwayplot:
    input:
        ne_files
    output:
        "homo_sapiens_Gutenkunst/estimated_Ne.png"
    run: plots.plot_compound_Ne_estimate(input, output[0])

rule clean:
    shell:
        "rm -rf stairwayplot stairwayplot.tar.gz"
        "rm -fr homo_sapiens_Gutenkunst"
